backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
#  - name: "blog"
#    label: "Blog"
#    folder: "src/pages/blog"
#    create: true
#    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
#    fields:
#      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
#      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Publish Date", name: "date", widget: "datetime"}
#      - {label: "Description", name: "description", widget: "text"}
#      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
#      - {label: "Featured Image", name: "featuredimage", widget: image}
#      - {label: "Body", name: "body", widget: "markdown"}
#      - {label: "Tags", name: "tags", widget: "list"}

  - name: "updates"
    label: "Updates"
    folder: "src/pages/updates"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
#      - {label: "Sticky Post", name: "stickypost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags",  name: "tags", widget: "list", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
#          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: About, name: about, widget: object, fields: [
                {label: Heading, name: heading, widget: string},
                {label: Description, name: description, widget: text},
                {label: Partners, name: partners, widget: markdown}
            ]}
          - {label: Activities, name: activities, widget: object, fields: [
                {label: Heading, name: heading, widget: string},
                {label: Workstreams, name: workstreams, widget: list, fields: [
                    {label: Tag, name: tag, widget: string},
                    {label: Title, name: title, widget: string},
                    {label: Description, name: description, widget: text},
                    {label: Icon, name: icon, widget: image}
                ]}
            ]}
          - {label: Updates, name: updates, widget: object, fields: [
                {label: Heading updates, name: headingUpdates, widget: string},
                {label: Heading twitter, name: headingTwitter, widget: string},
                {label: Twitter account, name: twitterAccount, widget: string}
            ]}
          - {label: Team, name: team, widget: object, fields: [
                {label: Heading, name: heading, widget: string},
                {label: Team members, name: teamMembers, widget: list, fields: [
                    {label: Name, name: name, widget: string},
                    {label: Bio, name: bio, widget: text},
                    {label: Twitter, name: twitter, widget: text, required: false},
                    {label: LinkedIn, name: linkedin, widget: text, required: false},
                    {label: Image, name: image, widget: image}
                ]}
            ]}
          - {label: Resources, name: resources, widget: object, fields: [
                {label: Background readings, name: backgroundReadings, widget: object, fields: [
                    {label: Heading , name: heading, widget: string},
                    {label: Readings, name: readings, widget: list, fields: [
                        {label: Author, name: author, widget: string},
                        {label: Title, name: title, widget: string},
                        {label: Text, name: text, widget: markdown}
                    ]}
                ]},
                {label: Related initiatives, name: relatedInitiatives, widget: object, fields: [
                    {label: Heading , name: heading, widget: string},
                    {label: Initiatives, name: initiatives, widget: list, fields: [
                        {label: Title, name: title, widget: string},
                        {label: Text, name: text, widget: text},
                    ]}
                ]}
            ]}
          - {label: Footer, name: footer, widget: object, fields: [
              {label: Imprint, name: imprint, widget: object, fields: [
                  {label: Heading , name: heading, widget: string},
                  {label: Text, name: text, widget: markdown}
              ]},
              {label: Disclaimer, name: disclaimer, widget: object, fields: [
                  {label: Heading , name: heading, widget: string},
                  {label: Text, name: text, widget: markdown}
              ]},
              {label: Privacy policy, name: privacy, widget: object, fields: [
                  {label: Heading , name: heading, widget: string},
                  {label: Text, name: text, widget: markdown}
              ]}
          ]}

#      - file: "src/pages/about/index.md"
#        label: "About"
#        name: "about"
#        fields:
#          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
#          - {label: "Title", name: "title", widget: "string"}
#          - {label: "Body", name: "body", widget: "markdown"}
#      - file: "src/pages/products/index.md"
#        label: "Products Page"
#        name: "products"
#        fields:
#          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
#          - {label: Title, name: title, widget: string}
#          - {label: Image, name: image, widget: image}
#          - {label: Heading, name: heading, widget: string}
#          - {label: Description, name: description, widget: string}
#          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
#          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
#          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
#          - {label: Full_image, name: full_image, widget: image}
#          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
